import React, { useState, useEffect } from 'react'
import './popup.css'
import axios from 'axios';
import RingLoader from "react-spinners/RingLoader";
import Button from '@mui/material/Button';
import LiveTvIcon from '@mui/icons-material/LiveTv';


const MovieProfile = ({ movie, close }) => {
  const [story, setStory] = useState('');
  const [loading, setLoading] = useState(true);
  const [actors, setActors] = useState([]);


  useEffect(() => {
    async function generateStory() {
      try {
        const response = await axios.post('https://api.openai.com/v1/engines/text-davinci-002/completions', {
          prompt: `Write a story about ${movie.title} movie, which was released in ${movie.release_date}`,
          temperature: 0.9,
          max_tokens: 500,
        }, {
          headers: {
            'Authorization': `Bearer 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`,
            'Content-Type': 'application/json',
          },
        });
        setStory(response.data.choices[0].text);
        setLoading(false);
      } catch (error) {
        console.error('error:' + error);
      }
    }
    async function fetchActors() {
      try {
        const response = await axios.get(`https://api.themoviedb.org/3/movie/${movie.id}/credits?api_key=0cb0cf970fcbb3d0a9b2403923eceae9`);
        setActors(response.data.cast.slice(0, 8));
      } catch (error) {
        console.error('error:' + error);
      }
    }

    generateStory();
    fetchActors();
  }, [movie.Title]);

  return (
    <div className='overlay'>
      <div className='modalContainer'>
        <button className="closeButton" onClick={close}>X</button>
        <div className="modalHeader">
          <span className="modalTitle">{movie.title}</span><span>({movie.release_date.slice(0, 4)})</span>
        </div>

        <div className="posterAndActors">
          <div className='left'>
            <img src={`https://image.tmdb.org/t/p/w500${movie.poster_path}`} alt={movie.title} />
          </div>
          <div className="right">
            <div className="actors">
              <h2>Actors</h2>
              {actors.map(actor => (
              <div className="actor">
                <p>{actor.name}</p>
              </div>
              ))}
            </div>
            
              <h2>Story</h2><span>(Generated by OpenAI, maybe it is not accurate)</span>
            <div className="story">
              {loading ? <RingLoader color="#1976d2" /> : <p>{story}</p>}
            </div>
            <div>
              <Button 
                style={{marginTop: '10px'}}
                variant="contained"
                endIcon={<LiveTvIcon />}
                onClick={() => {
                  const title = movie.title.replace(/ /g, '-');
                  window.open(`https://solarmovie.pe/search/${title}/`, '_blank');
                }}
              >
                Watch
              </Button>
            </div>
          </div>
          
        </div>
          
      </div>
    </div>
  );
};

export default MovieProfile;
